name: SeriaCrate
version: 1.1.0
main: id.seria.crate.SeriaCrate
api-version: '1.21'
author: Project Seria Dev
description: Ultimate Crate Reward System with Gacha Animation
softdepend: [MMOItems, EcoPets, Vault, PlaceholderAPI]

commands:
  seriacrate:
    description: Admin commands for SeriaCrate
    permission: seriacrate.admin
    aliases: [scrate]
  opencrate:
    description: Open the crate UI
  scrate:
    description: Main command for SeriaCrate
    permission: seriacrate.admin
  resin:
    description: Mengecek jumlah dan waktu regen resin
    aliases: [stamina]
  resinadmin:
    description: Manajemen resin player
    permission: seriacrate.admin