# ==========================================
# PROJECT SERIA - MAIN CONFIGURATION
# ==========================================

settings:
  prefix: "&7&9&1&E&F&Fᴘʀᴏᴊᴇᴄᴛ ꜱᴇʀɪᴀ &7» "
  # Berapa Gins yang dibutuhkan untuk buka crate (jika pakai sistem bayar)
  crate-cost: 20
  # Delay sebelum rolling dimulai (ticks)
  start-delay-ticks: 5
  # Durasi maksimal animasi putaran (ticks)
  max-rolling-duration-ticks: 60

resin:
  enabled: true
  max: 160
  regen-minutes: 3

temporary-crate:
  enabled: true
  # Berapa lama peti muncul di dunia sebelum hilang
  duration-seconds: 180 

# Integrasi Plugin Luar
hooks:
  mmoitems: true
  ecopets: true
  vault: true

GUI:
  # Format judul saat pemain membuka crate. Sangat penting untuk mencegah bug klik!
  # Variabel yang tersedia: %boss% (Nama Boss), %tier% (Tier)
  # JANGAN hapus kata "Reward Crate", karena digunakan sistem untuk memblokir klik pemain.
  TitleFormat: "&8| Reward Crate %boss% - Tier %tier%"

resin-items:
  infused-resin:
    material: "mmoitems-CONSUMABLE:INFUSEDRESIN"
    amount: 20

  